services:
  postgres:
    image: postgres:13
    container_name: gestion_postgres
    environment:
      POSTGRES_USER: IN6AV
      POSTGRES_PASSWORD: Hoc41509
      POSTGRES_DB: gestion_opinions
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: